data:
  menus:
    - name: 项目
      id: project
      path: /project
      icon: OrderedListOutlined
      perm-codes: [project:view,project:save,project:delete,project:build]
      perm-names: [查看,保存,删除,构建]
    - name: 应用
      id: app
      path: /app
      icon: AppstoreOutlined
      perm-codes: [app:view,app:save,app:config,app:delete,app:deploy]
      perm-names: [查看,保存,配置,删除,部署]

    - name: 其他
      id: config
      icon: SettingOutlined
      children:
        - name: 主机
          id: host
          path: /host
          icon: DesktopOutlined
          perm-codes: [host:list,host:save,host:delete]
          perm-names: [查看,保存,删除]

