## docker-admin 业务菜单
menus:
  biz:
    name: 容器平台
    icon: AppstoreOutlined
    seq: 10
  project:
    pid: biz
    name: 项目
    path: /project
    icon: ContainerOutlined
    seq: 150
    perms:
      - {name: 查看, code: project:view}
      - {name: 保存, code: project:save}
      - {name: 删除, code: project:delete}
      - {name: 构建, code: project:build}
      - {name: Webhook, code: project:webhook}
  image-repo:
    pid: biz
    name: 镜像仓库
    path: /image-repo
    icon: ContainerOutlined
    seq: 100
    perms:
      - {name: 查看, code: image-repo:view}
      - {name: 删除, code: image-repo:delete}
  divider-image-repo:
    pid: biz
    type: divider
    seq: 120
  app:
    pid: biz
    name: 应用
    path: /app
    icon: AppstoreOutlined
    seq: 200
    perms:
      - {name: 查看, code: app:view}
      - {name: 保存, code: app:save}
      - {name: 配置, code: app:config}
      - {name: 删除, code: app:delete}
      - {name: 部署, code: app:deploy}
      - {name: 隧道, code: app:tunnel}
  divider-app:
    pid: biz
    type: divider
    seq: 250
  setting:
    pid: biz
    name: 设置
    icon: SettingOutlined
    seq: 400
  host:
    pid: setting
    name: 主机管理
    path: /host
    icon: DesktopOutlined
    seq: 450
    perms:
      - {name: 查看, code: host:list}
      - {name: 保存, code: host:save}
      - {name: 删除, code: host:delete}
  setting-registry:
    pid: setting
    name: 注册中心
    path: /registry
    icon: CloudServerOutlined
    seq: 500
    perms:
      - {name: 查看, code: registry:view}
      - {name: 保存, code: registry:save}
  setting-code-source:
    pid: setting
    name: 代码源
    path: /code-source
    icon: KeyOutlined
    seq: 600
    perms:
      - {name: 查看, code: code-source:view}
      - {name: 保存, code: code-source:save}
      - {name: 删除, code: code-source:delete}
  tool:
    pid: biz
    name: 辅助工具
    icon: ToolOutlined
    seq: 700
  setting-sync:
    pid: tool
    name: 镜像同步
    path: /image-sync
    icon: CloudSyncOutlined
    seq: 100
    perms:
      - {name: 查看, code: image-sync:view}
      - {name: 同步, code: image-sync:sync}
  build-test:
    pid: tool
    name: 构建测试
    path: /build-test
    icon: BuildOutlined
    seq: 200
    perms:
      - {name: 查看, code: build-test:view}
      - {name: 构建, code: build-test:build}
      - {name: 写入仓库, code: build-test:write}
  tunnel:
    pid: tool
    name: 隧道管理
    path: /tunnel
    icon: ApiOutlined
    seq: 300
    perms:
      - {name: 查看, code: tunnel:view}
      - {name: 客户端, code: tunnel:save}
