name: Jar

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - name: 前端构建
      run: cd web && npm install && npm run build

    - name: 复制前端文件到后端源码
      run: cp -r web/dist/* src/main/resources/static

    - name: 后端构建
      run: mvn package

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: target/app.jar

    


